# -*- coding: utf-8 -*-
{
    'name': "WS: Setting Contact from Email Received to Helpdesk Ticket",

    'summary': """Auto sets the search member field to the partner who's phone number is noted by voip in chatter""",

    'description': """
        Task ID: 2279781
        Specific helpdesk team will be receiving emails to the assigned email address in the team, emails received here create a helpdesk ticket.
        This ticket created is named after the subject included in the email received.
        Emails sent to this address are going to be generated by the customer's VOIP only and will always have the same structure, including in the body the "caller ID" 
        which is the phone that called them.
        Inside the ticket we have the "search member" field, which is the Odoo Contact or partner_id for the ticket, this contact has a phone number assigned to them.
        We want Odoo to search for the contact that has that phone number assigned to them and set it on the "search member" / partner_id field, if the system finds 
        more than 1 contact with that phone number inside them then the contact set should be the one with the highest age value.
    """,

    'author': "Odoo Inc",
    'website': "http://www.odoo.com",
    'category': 'Custom Developmemt',
    'version': '1.0',
    'license': 'OEEL-1',
    'depends': ['helpdesk'],
    'data': [
        'views/res_config_settings_views.xml',
        'views/helpdesk_form.xml'
    ]
}
